# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
- stage: Terraform Init
  jobs:
  - job:
    steps:
    - bash: terraform init
      displayName: 'Running Terraform init'
      
- stage: Terraform plan
  jobs:
  - job:
    steps:
    - bash: terraform plan
      displayName: 'Running Terraform plan'

- stage: Terraform Apply
  jobs:
  - job:
    steps:
    - bash: terraform apply -auto-approve
      displayName: 'Running terraform apply'



